# Generated by Django 3.1.4 on 2020-12-07 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_activation'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueuedEmail',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('subject', models.CharField(max_length=100)),
                ('template', models.CharField(max_length=100)),
                ('data', models.JSONField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Activation',
        ),
    ]
