# Generated by Django 3.1.4 on 2020-12-09 12:50

from django.db import migrations
from django_q.tasks import schedule

def create_email_schedule(apps, schema_editor):
    # TODO: make interval convigurable
    schedule('alu.emailer.tasks.send_emails', schedule_type='I', minutes=1)
    
class Migration(migrations.Migration):

    dependencies = [
        ('emailer', '0001_initial'),
        ('django_q', '0013_task_attempt_count'),
    ]

    operations = [
        migrations.RunPython(create_email_schedule)
    ]
